# 线上配置文件
# 
# 
server:
  port: 7080
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jinx_bi
    username:
    password:
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
  # password: 123456
  # Elasticsearch 配置
  # todo 需替换配置
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456
  rabbitmq:
    host: localhost
    port: 5672
    username:
    password:
    virtual-host: /
    #    publisher-confirm-type: correlated
    #    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual # 表示消息确认方式，其有三种配置方式，分别是none、manual（手动ack）和auto；默认auto
        concurrency: 5         # 最小的消费者数量
        max-concurrency: 10    # 最大的消费者数量
        prefetch: 3            # 指定一个请求能处理多少个消息，如果有事务的话，必须大于等于transaction数量.
        # 重试机制：
        #         eg: 最大重试次数为8 & 重试间隔1秒 & 间隔时间乘子2 & 最大间隔时间50秒  -- (最大重试次数包含初次消费)
        #         初次消費
        #         第1次：1秒
        #         第2次：1*2=2秒
        #         第3次：2*2=4秒
        #         第4次：4*2=8秒
        #         第5次：8*2=16秒
        #         第6次：16*2=32秒
        #         第7次：32*2=64秒 (由于设置最大间隔时间，因此这里为50秒 )
        retry:
          enabled: true          # 是否开启重试
          max-attempts: 4        # 最大重试次数
          max-interval: 50000    # 重试最大间隔时间
          initial-interval: 1000 # 重试间隔（单位：毫秒）
          multiplier: 2          # 间隔时间乘子，间隔时间*乘子=下一次的间隔时间，最大不能超过设置的最大间隔时间
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
yuapi:
  client:
    access-key: k2w8j964f62i7itiun9hxpr5dic7kgf4
    secret-key: 9yjpy39nd2p61bcfex24cr9hlbgemlve